---
- name: Configure systemd journald.conf
  become: true
  ansible.builtin.template:
    src: "{{ journald_conf_template }}"
    dest: /etc/systemd/journald.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd
  tags:
    - systemd
    - journald
    - CIS-UBUNTU2004-4.2.2.1
    - CIS-UBUNTU2004-4.2.2.2
    - CIS-UBUNTU2004-4.2.2.3

- name: Disable systemd-journal-remote
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  loop:
    - systemd-journal-remote.socket
    - systemd-journal-remote.service
  register: mask_journal_remote
  failed_when:
    - mask_journal_remote is not success
    - not "Could not find the requested service" in mask_journal_remote.msg
  when:
    - ansible_virtualization_type not in ["container", "docker", "podman"]
  tags:
    - systemd
    - journald

- name: Configure logrotate(8)
  become: true
  ansible.builtin.template:
    src: "{{ logrotate_conf_template }}"
    dest: /etc/logrotate.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  tags:
    - logrotate

- name: Configure cron.daily logrotate
  become: true
  ansible.builtin.lineinfile:
    line: /usr/sbin/logrotate /etc/logrotate.conf
    dest: /etc/cron.daily/logrotate
    mode: "0750"
    state: present
    create: true
  when:
    - ansible_os_family != 'Suse'
  tags:
    - cron
    - logrotate

- name: Stat rsyslog.conf
  become: true
  ansible.builtin.stat:
    path: /etc/rsyslog.conf
  register: rsyslogconf
  tags:
    - rsyslog

- name: Stat rsyslog.d
  become: true
  ansible.builtin.stat:
    path: /etc/rsyslog.d
  register: rsyslogd
  tags:
    - rsyslog

- name: Set rsyslog FileCreateMode
  become: true
  block:
    - name: Configure rsyslog.conf FileCreateMode
      ansible.builtin.lineinfile:
        regexp: ^\$FileCreateMode
        line: $FileCreateMode {{ rsyslog_filecreatemode }}
        dest: /etc/rsyslog.conf
        mode: "0640"
        state: present
        create: false
      when:
        - rsyslogconf.stat.exists
      notify:
        - Validate rsyslogd
      tags:
        - rsyslog
        - CIS-UBUNTU2004-4.2.1.4

    - name: Add FileCreateMode file to the rsyslog.d directory
      ansible.builtin.lineinfile:
        regexp: ^\$FileCreateMode
        line: $FileCreateMode {{ rsyslog_filecreatemode }}
        dest: /etc/rsyslog.d/99-filecreatemode.conf
        mode: "0644"
        state: present
        create: true
      when:
        - rsyslogd.stat.exists
        - rsyslogd.stat.isdir
      notify:
        - Validate rsyslogd
      tags:
        - rsyslog
